CREATE TABLE vinkosdb.errores (
	idError INT AUTO_INCREMENT PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    nameRegister VARCHAR(100) NOT NULL,
    messageError VARCHAR(255) NOT NULL
);